apiVersion: v1
data:
  prometheus.yml: |
    global: 
      scrape_interval: 15s

    scrape_config:
    - job_name: prometheus
      static_configs:
      - targets: ['localhost:9090']
kind: ConfigMap
metadata:
  name: prometheus
